# Generated by Django 6.0 on 2025-12-18 08:29

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cart_id_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.CharField(default=store.models.generate_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
