# Generated by Django 6.0 on 2026-01-22 17:47

import store.validatores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/images/', validators=[store.validatores.validate_file_size]),
        ),
    ]
